/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CubingIcons
///      fonts:
///       - asset: fonts/CubingIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SizeIcons {
  SizeIcons._();

  static const fontFamily = 'CubingIcons';

  static const IconData size2 = IconData(0xe800, fontFamily: fontFamily);
  static const IconData size3 = IconData(0xe801, fontFamily: fontFamily);
  static const IconData size4 = IconData(0xe807, fontFamily: fontFamily);
  static const IconData size5 = IconData(0xe809, fontFamily: fontFamily);
  static const IconData size6 = IconData(0xe80b, fontFamily: fontFamily);
  static const IconData size7 = IconData(0xe80c, fontFamily: fontFamily);
}