/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CubingIcons
///      fonts:
///       - asset: fonts/CubingIcons.ttf
///
/// 
///
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

class SizeIcons {
  SizeIcons._();

  static const fontFamily = 'CubingIcons';

  static const IconData size2 = IconData(0xe800, fontFamily: fontFamily);
  static const IconData size3 = IconData(0xe801, fontFamily: fontFamily);
  static const IconData size4 = IconData(0xe807, fontFamily: fontFamily);
  static const IconData size5 = IconData(0xe809, fontFamily: fontFamily);
  static const IconData size6 = IconData(0xe80b, fontFamily: fontFamily);
  static const IconData size7 = IconData(0xe80c, fontFamily: fontFamily);
}

class SizeIconsWidget extends StatelessWidget {
  SizeIconsWidget(this.currentSize,this.onPressed,{ Key? key }) : super(key: key);
  final int currentSize;
  final Function(int newSize) onPressed;

  final List<IconData> sizeIcons = [SizeIcons.size2,SizeIcons.size3,SizeIcons.size4,
    SizeIcons.size5,SizeIcons.size6];

  @override
  Widget build(BuildContext context) {
    SharedPreferences? prefs = context.watch<SharedPreferences?>();
    if(prefs == null) {
      return Container();
    }
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        for(int i=0; i<sizeIcons.length; i++)
          Opacity(
            opacity: i+2 == currentSize ? 1.0 : 0.5,
            child: Padding(
              padding: const EdgeInsets.all(8.0),
              child: InkWell(
                child: Column(
                  children: [
                    Icon(sizeIcons[i],size: 60,),
                    Text("Best: "+(prefs.getInt("pb${i+2}")?.toString() ?? "N/A"))
                  ],
                ),
                onTap: (){
                  if(i+2 != currentSize)
                    onPressed(i+2);
                },
              ),
            )
          )
      ],
    );
  }
}